#!/bin/sh

codedir=$1

if [[ -f $codedir/diff.txt ]]; then
  rm -rf $codedir/diff.txt
fi
if [[ -f $codedir/modifiedFuncs.txt ]]; then
  rm -rf $codedir/modifiedFuncs.txt
fi
if [[ -f $codedir/useCase.txt ]]; then
  rm -rf $codedir/useCase.txt
fi

cd $codedir
doxygen
cd ..

git diff HEAD -- $codedir >> $codedir/diff.txt

./DoxygenParse.exe $codedir f
./DoxygenParse.exe $codedir g

strindex() { 
  x="${1%%$2*}"
  [[ $x = $1 ]] && index=-1 || index=${#x}
}

while read line           
do           
    if [[ "$line" == "diff --git a/$codedir"* ]]; then
		b=" b/"
		strindex "$line" "$b" 
		filename=${line:14+${#codedir}:$index-15-${#codedir}+1}
		echo $filename
		echo " " >> $codedir/modifiedFuncs.txt
		echo "$filename" >> $codedir/modifiedFuncs.txt
	fi
	
	if [[ "$line" == "@@"* ]]; then
		strindex "$line" "+"
		cutline=${line:0:$index}
		strindex "$cutline" ","
		if [ $index -ge 0 ]; then
			num1=${cutline:4:$index-4}
			cutline=${cutline:$index+1:${#cutline}-$index}
			strindex "$cutline" " "
			num2=${cutline:0:$index}
		else
			strindex "$line" "-"
			cutline=${line:$index+1:${#line}-$index}
			strindex "$cutline" " "
			num1=${cutline:0:$index}
			num2=$num1
		fi
		strindex "$line" "+"
		cutline=${line:$index+1:${#line}-$index}
		strindex "$cutline" ","
		if [ $index -lt 0 ]; then
			strindex "$cutline" " "
			num3=${cutline:0:$index}
			num4=$num3
		else
			num3=${cutline:0:$index}
			cutline=${cutline:$index+1:${#cutline}-$index}
			strindex "$cutline" " "
			num4=${cutline:0:$index}
		fi
		sum1=$((num1+num2))
		sum2=$((num3+num4))
		echo "$num1,$sum1" >> $codedir/modifiedFuncs.txt
		echo "$num3,$sum2" >> $codedir/modifiedFuncs.txt
	fi
done <$codedir/diff.txt 

rm -rf $codedir/diff.txt

methods=0
while read line
do
	if [[ "$line" == *"<useCase>"* ]]; then
		read line
		strindex "$line" "<name>"
		index1=$((index+6))
		strindex "$line" "</name>"
		index2=$index
		useCaseName=${line:$index1:$index2-$index1}
	elif [[ "$line" == *"<method>"* ]]; then
		strindex "$line" "<method>"
		index1=$((index+8))
		strindex "$line" "</method>"
		index2=$index
		methodSig=${line:$index1:$index2-$index1}
		strindex "$methodSig" "::"
		index1=$((index+2))
		strindex "$methodSig" "("
		index2=$index
		if [[ $index -lt 0 ]]; then
			index2=${#methodSig}
		fi
		methodName=${methodSig:$index1:$index2-$index1}
		strindex "$methodSig" " "
		index1=$((index+1))
		strindex "$methodSig" "::"
		fileName=${methodSig:$index1:$index-$index1}
		array[$methods]="$useCaseName|$fileName|$methodName"
		methods=$methods+1
	fi
done <$codedir/input.xml

for line in "${array[@]}"; do
	echo $line >> $codedir/useCase.txt
done

modCount=0
while read line
do
	if [[ -z "$line" ]]; then
		read line
		fileName=$line
		fileName=${fileName//\//\\}
	else
		strindex "$line" ","
		modStart=${line:0:$index}
		modFin=${line:$index+1:${#line}-$index}
		while read -r line
		do
			if [[ "$line" == "$fileName"* ]]; then
				strindex "$line" " "
				space=$index
				strindex "$line" "-"
				dash=$index
				metStart=${line:$space+1:$dash-$space-1}
				cutline=${line:$dash+1:${#line}-$dash}
				strindex "$cutline" " "
				space=$index
				metFin=${cutline:0:$space}
				methodName=${cutline:$space+1:${#cutline}-$space}
				if [ $((modStart)) -le $((metStart)) ] && [ $((modFin)) -ge $((metStart)) ]; then
					modified[modCount]="$fileName|$methodName"
					modCount=$modCount+1
				elif [ $((modFin)) -ge $((metFin)) ] && [ $((modStart)) -le $((metFin)) ]; then
					modified[modCount]="$fileName|$methodName"
					modCount=$modCount+1
				elif [ $((metStart)) -le $((modStart)) ] && [ $((metFin)) -ge $((modStart)) ]; then
					modified[modCount]="$fileName|$methodName"
					modCount=$modCount+1
				elif [ $((metFin)) -ge $((modFin)) ] && [ $((metStart)) -le $((modFin)) ]; then
					modified[modCount]="$fileName|$methodName"
					modCount=$modCount+1
				fi
			fi
		done <$codedir/functions.txt
	fi
done <$codedir/modifiedFuncs.txt

modlist=$(echo "${modified[@]}" | sed 's/ /\n/g' | sort -u )
modlist=$(echo $modlist)
rm -rf $codedir/modifiedFuncs.txt

strindex "$modlist" " "
space=$index
while [[ $space -ge 0 ]]; do
	substring=${modlist:0:$index}
	echo $substring >> $codedir/modifiedFuncs.txt
	modlist=${modlist:$index+1:${#modlist}-$index}
	strindex "$modlist" " "
	space=$index
done
echo $modlist >> $codedir/modifiedFuncs.txt

./DoxygenParse.exe $codedir s ./$codedir/useCase.txt ./$codedir/modifiedFuncs.txt >> useCasesAffected.txt